### ISSUE TITLE
Recursion Error

### ISSUE THREAD

**Issue by bastisawesome** [flask-admin/flask-admin#1641]
```
Traceback (most recent call last):
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_admin/base.py", line 452, in index
    return self.render(self._template)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/bast/microblog/app/templates/admin/index.html", line 1, in top-level template code
    {% extends 'admin/master.html' %}
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 6, in top-level template code
    <title>{% block title %}{% if admin_view.category %}{{ admin_view.category }} - {% endif %}{{ admin_view.name }} - {{ admin_view.admin.name }}{% endblock %}</title>
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 6, in block "title"
    <title>{% block title %}{% if admin_view.category %}{{ admin_view.category }} - {% endif %}{{ admin_view.name }} - {{ admin_view.admin.name }}{% endblock %}</title>
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 133, in __str__
    return str(self.value)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/speaklater.py", line 115, in <lambda>
    value = property(lambda x: x._func(*x._args, **x._kwargs))
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_babelex/__init__.py", line 533, in gettext
    t = self.get_translations()
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_babelex/__init__.py", line 510, in get_translations
    locale = get_locale()
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask_babelex/__init__.py", line 220, in get_locale
    rv = babel.locale_selector_func()
  File "/home/bast/microblog/app/__init__.py", line 97, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/flask/globals.py", line 35, in _lookup_req_object
    top = _request_ctx_stack.top
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/werkzeug/local.py", line 166, in top
    return self._local.stack[-1]
  File "/home/bast/.virtualenvs/bast-forums/lib/python3.6/site-packages/werkzeug/local.py", line 70, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
```

Not sure what's going on. Everything was running fine until I installed Flask Security, but it only errors in the admin link.

**Comment by bastisawesome** [comment]
So, while debugging it seems that the issue is specifically with Flask-Babel. Not sure if there's a fix for this, but until I know how, I guess I will be removing the locale detection code.

```python
#Configure current locale
@babel.localeselector
def get_locale():
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])```

**Comment by artyomLisovskij** [comment]
Same issue
@bastisawesome thank you!
But how to make it work together?

**Comment by aribo** [comment]
I have the same issue. No idea what's causing it. So far I found that taking out variables {{ admin_view.admin.name }} from base.html and {{ item.name }} from layout.html removes the issue, but the menu items cannot be referenced in the layout. It seems there's something between 'name' in flask-admin templates and 'name in the speaklater function (return getattr(self.value, name))

**Comment by aribo** [comment]
actually, in base.html is {{ admin_view.name }} in <title>

**Comment by aribo** [comment]
Ok, now I changed the variable 'name' in the class BaseMenu in menu.py of flask-admin to 'title'. This worked. Now it doesn't give a recursive error for the layout. I'll do the same for the admin_view variable.

**Comment by aribo** [comment]
I think I solved it.

I had the same issue with flask-babel and flask-admin. I followed Miguel Grinberg's tutorial to install flask-babel, using the get_locale function and settings LANGUAGE= ['en', 'es']. The error was only happening in Chrome and Brave (which is based on Chrome), not in Safari. I think I solved it. I changed the language codes to the full code en > en-EN and es > es-ES and the issue is gone. It seems that Chrome interprets differently the short codes. I don't really know the cause, just happy I solved it.

**Comment by albatros69** [comment]
Hello,
This issue is still pending and I've been bitten by it recently. Since the workaround mentioned (using Flask-BabelEx instead of Flask-Babel) relies on a module which seems now abandoned (archived repository), I'm wondering if there's a proper solution.

Thanks in advance,

**Comment by Edvaytech** [comment]
Hi all,
I also got the same issue i m using flask-babel and flask-admin together and same thing happened when i remove locale detection code it's working fine and error will occur when i try to access /admin.

**Comment by Edvaytech** [comment]
Hi all,
I also got the same issue i m using flask-babel and flask-admin together and same thing happened when i remove locale detection code it's working fine and error will occur when i try to access /admin.

**Comment by fagcinsk** [comment]
Resolved by uninstalling flask-babelex, but now translations not works, but determined by `babel.list_translations()`.

**Comment by klconur** [comment]
> Resolved by uninstalling flask-babelex, but now translations not works, but determined by `babel.list_translations()`.

@fagci this solution worked for me.

**Comment by animax1991** [comment]
> I think I solved it @bastisawesome and @artyomLisovskij
> 
> I had the same issue with flask-babel and flask-admin. I followed Miguel Grinberg's tutorial to install flask-babel, using the get_locale function and settings LANGUAGE= ['en', 'es']. The error was only happening in Chrome and Brave (which is based on Chrome), not in Safari. I think I solved it. I changed the language codes to the full code en > en-EN and es > es-ES and the issue is gone. It seems that Chrome interprets differently the short codes. I don't really know the cause, just happy it's gone.

Not worked for me.

4 years later, the problem is still exist. It seem like flask-admin is abandoned. Is there any solution for this until now? Or I have to switch to another admin library?

**Comment by baranyeni** [comment]
Also fixed via switching to https://pypi.org/project/Flask-BabelEx/ from https://pypi.org/project/Flask-Babel

**Comment by ElLorans** [comment]
I cannot reproduce the issue with flask-babel while flask-babelex is deprecated since all changes have been merged to flask-babel. I am closing but happy to reopen if you still experience this.
