### ISSUE TITLE
Edit form broken when using 1 boolean field

### ISSUE THREAD

**Issue by matteosimone** [flask-admin/flask-admin#681]
When using an edit form and having only 1 boolean field, unchecking the boolean does not save to the model after submitting the form.

Sample app: https://gist.github.com/matteosimone/3dfd4889261d171d2112

Go to http://localhost:5000/admin/modelview/ after running and try to edit the model to uncheck the boolean and submit.

**Comment by dchaplinsky** [comment]
This solution doesn't work anymore.

Here is my attempt:
```
class RequiredBooleanField(wtforms.fields.SelectField):
    # wtforms/flask-admin has a flaw related
    # to boolean fields with required=True in the model
    # Ultimatelly false values wouldn't pass validation of the form
    # thus the workaround
    def __init__(self, *args, **kwargs):
        choices = [
            (True, "True"),
            (False, "False"),
        ]

        kwargs["choices"] = choices
        kwargs["coerce"] = lambda x: str(x) == "True"

        super(RequiredBooleanField, self).__init__(*args, **kwargs)
```

and then you use it like this:
```
class WhateverAdmin(ModelView):
    form_overrides = {
        "my_required_field": RequiredBooleanField,
    }
```

**Comment by petrus-jvrensburg** [comment]
thanks @matteosimone, this has been fixed

**Comment by seanmajorpayne** [comment]
@petrus-jvrensburg This issue is still present. I am currently dealing with the same problem and neither of the solutions posted above are solving this issue.

**Comment by jonalxh** [comment]
Im facing the same issed.

**Comment by yassineim** [comment]
This worked for me:
```
form_widget_args = {
    'first_field': {
        'required': False
    }, 'second_field': {
        'required': False
    }
}
```
